[settings.github]
github_attestations = false

[tools]
erlang = "latest"
elixir = "latest"
node = "latest"
python = "latest"
neovim = "latest"
tree-sitter = "latest"
bun = "latest"
"ubi:elixir-lang/expert" = "nightly"
"github:cli/cli" = "latest"
"aqua:ankitpokhrel/jira-cli" = "latest"
awscli = "latest"
claude-code = "latest"
"ubi:Foxboron/ssh-tpm-agent" = "0.8.0"
"github:Foxboron/ssh-tpm-agent" = "0.8.0"
