font_family MonoLisa Custom
font_size 13.5
clipboard_control write-clipboard write-primary no-append
hide_window_decorations titlebar-only
window_padding_width 10

map alt+backspace send_text all \x17
map super+backspace send_text all \x15
map super+left send_text all \x01
map super+right send_text all \x05
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

map super+1 goto_tab 1
map super+2 goto_tab 2
map super+3 goto_tab 3
map super+4 goto_tab 4
map super+5 goto_tab 5
map super+6 goto_tab 6
map super+7 goto_tab 7
map super+8 goto_tab 8
map super+9 goto_tab 9

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

map ctrl+- launch --location=split --cwd=current

background           #fdf6e3
foreground           #52676f
cursor               #52676f
selection_background #e9e2cb
color0               #e4e4e4
color8               #ffffd7
color1               #d70000
color9               #d75f00
color2               #5f8700
color10              #585858
color3               #af8700
color11              #626262
color4               #0087ff
color12              #808080
color5               #af005f
color13              #5f5faf
color6               #00afaf
color14              #8a8a8a
color7               #262626
color15              #1c1c1c
selection_foreground #fcf4dc
