alias gco "git checkout"
alias gst "git status -sb"
alias gc "git commit"
alias gcm "git commit -m"
alias ga "git add"
alias gaa "git add -A"
alias gap "git add --patch"
alias gpl "git pull -r"
alias gps "git push"
alias gl "git log --oneline"
