" Setup Pathogen
source ~/.dotfiles/vim/pathogen/autoload/pathogen.vim

" Keyboard mods
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
map <C-h> <C-W>h
map <C-l> <C-W>l
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
map <C-b> :NERDTreeToggle<CR>

" Settings
set backspace=indent,eol,start
set omnifunc=syntaxcomplete#Complete
syntax on
set smartindent
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set number
set cursorline
set showmatch
set incsearch
set hlsearch
let g:ctrlp_working_path_mode = 'r'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/node_modules/* " lol
let g:ctrlp_show_hidden=1
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
set noswapfile

" Start Pathogen
execute pathogen#infect('bundle/{}', '~/.dotfiles/vim/{}')
call pathogen#helptags()

" Colorscheme
set noruler
set noshowmode
set hidden

